title: After Coffee
owner: Gregory Daynes
email: contact@after.coffee
description: >-
  Development paired with coffee.
baseurl: ""
url: "https://after.coffee"
language: "en"
kramdown:
  parse_block_html: true
sass:
  style: compressed
permalink: /:title/index.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Gregory Daynes

plugins:
  - jekyll-sitemap
  # - jekyll-feed
  - jekyll-seo-tag
