name: After Coffee
owner: Gregory Daynes
email: contact@after.coffee
tagline: >-
  Code to go with your coffee.
description: >-
  Essays to snippets, writings related to software development.
baseurl: ""
url: "https://after.coffee"
language: "en"
kramdown:
  parse_block_html: true
sass:
  style: compressed
permalink: /:title/index.html
source: ./src
timezone: America/Pacific
encoding: utf-8
livereload: true
author:
  name: Gregory Daynes
  url: https://github.com/gregdaynes
  avatar: https://s.gravatar.com/avatar/64219f714a97767504935784ea1b7236?s=80
twitter:
  card: summary
  username: gregdaynes
social:
  name: Gregory Daynes
  links:
    - https://twitter.com/gregdaynes
    - https://github.com/gregdaynes
    - https://keybase.io/gregdaynes
lang: en_CA
locale: en_CA

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Gregory Daynes

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-contentblocks
