title: After Coffee
owner: Gregory Daynes
email: contact@after.coffee
tagline: >-
  Code paired with coffee.
description: ""
baseurl: ""
url: "after.coffee"
language: "en"
kramdown:
  parse_block_html: true
sass:
  style: compressed
permalink: /:title/index.html
source: ./src
timezone: America/Pacific
encoding: utf-8
livereload: true
autor: Gregory Daynes
twitter:
  card: summary
  username: gregdaynes
social:
  name: Gregory Daynes
  links:
    - https://twitter.com/gregdaynes
    - https://github.com/gregdaynes
    - https://keybase.io/gregdaynes
lang: en_CA
locale: en_CA

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Gregory Daynes

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-contentblocks
